Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/bionic64"

    config.vm.provider = "virtualbox" do |v|
	    v.memory = 4096
		v.cpus = 2
	end
	config.vm.provision "shell", inline:<<-SHELL
	    echo "updating system packages"
		sudo apt-get update
		sudo apt-get install -y python3-pip python3-dev curl
		
		echo "installing Test framework dependencies from requirements.txt"
		#/Vagrant points to the folder containing the Vagrantfile(i.e., environments)
		#So we look one level up to find requirements.txt in the root
		pip3 install -r /vagrant/../requirement.txt
		
		echo "VM environment setup completed successfully" 
	  SHELL
	end

 